// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for GcFunction
 */
export interface GcFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/Route53Writer/gc.
 */
export class GcFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: GcFunctionProps) {
    super(scope, id, {
      description: 'src/Route53Writer/gc.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs16.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/Route53Writer/gc.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}